// src/components/test-react.tsx
import React, {Component} from 'react'
import {randomNumber} from '../modules/tsModule'

interface State {
  counter: number
  text: string
}

class C extends Component<any, State> {
  constructor(props: any){
    super(props)

    this.state = {
      counter: 0,
      text: ''
    }
  }

  render(){
    const {counter, text} = this.state
    return (
      <div>
        {counter}
        <pre>
          {text}
        </pre>
      </div>
    )
  }

  componentDidMount(){
    setInterval(() => {
      this.setState({
        counter: this.state.counter + 1,
        text: randomNumber(0, 10) + ''
      })
    }, 1000)
  }
}

export default C

// src/components/test-vue.vue
<template>
  <div>
    {{counter}}
    <pre>
      {{text}}
    </pre>
  </div>
</template>

<script>
import commonModule from '../modules/commonModule'
export default {
  data(){
    return {
      counter: 0,
      text: commonModule
    }
  },
  created(){
    setInterval(() => {
      this.counter++
    }, 1000)
  }
}
</script>
